on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.x', '20.x', '21.x']
    steps:
    - uses: actions/checkout@v4
    - name: setup-node ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm i @web3-storage/w3cli
    - run: |
        npx w3 space add "$W3_PROOF"
      env:
        W3_PROOF: ${{ vars.W3_PROOF }}
        W3_PRINCIPAL: ${{ secrets.W3_PRINCIPAL }}
    - run: npm test
