on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

strategy:
  matrix:
    node-version: ['18.x', '20.x', '21.x']

steps:
- uses: actions/checkout@v4
- name: setup-node ${{ matrix.node-version }}
  uses: actions/setup-node@v4
  with:
    node-version: ${{ matrix.node-version }}
    cache: 'npm'
- run: npm install
- run: npm test

